import { createClient } from "@/lib/supabase/client"

const getClient = () => { const client = createClient(); if (!client) throw new Error("Supabase is not configured."); return client }
export async function hashInviteToken(token: string) { const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(token)); return Array.from(new Uint8Array(bytes), b => b.toString(16).padStart(2, "0")).join("") }
export async function createConnection(ownerId: string) { const { data, error } = await getClient().rpc("create_private_connection", { owner_id: ownerId }); if (error) throw error; return data as string }
export async function createInvite(connectionId: string, userId: string) { const token = crypto.randomUUID().replaceAll("-", ""); const { error } = await getClient().from("connection_invites").insert({ connection_id: connectionId, token_hash: await hashInviteToken(token), created_by: userId, expires_at: new Date(Date.now() + 604800000).toISOString() }); if (error) throw error; return token }
export async function saveQuestionAnswer(input: { connectionId: string; questionId: string; userId: string; answer: string }) { const { error } = await getClient().from("question_answers").upsert({ connection_id: input.connectionId, question_id: input.questionId, user_id: input.userId, answer: input.answer.trim(), updated_at: new Date().toISOString() }, { onConflict: "connection_id,question_id,user_id" }); if (error) throw error }
export async function addCustomQuestion(input: { connectionId: string; userId: string; prompt: string; isAdult: boolean }) { const { error } = await getClient().from("custom_questions").insert({ connection_id: input.connectionId, created_by: input.userId, prompt: input.prompt.trim(), is_adult: input.isAdult }); if (error) throw error }
export async function addLoreEntry(input: { connectionId: string; userId: string; title: string; body: string }) { const { error } = await getClient().from("lore_entries").insert({ connection_id: input.connectionId, created_by: input.userId, title: input.title.trim(), body: input.body.trim() }); if (error) throw error }
export async function saveReaction(input: { entryId: string; userId: string; reaction: string }) { const { error } = await getClient().from("lore_reactions").upsert({ entry_id: input.entryId, user_id: input.userId, reaction: input.reaction }, { onConflict: "entry_id,user_id" }); if (error) throw error }
export async function giveConsent(connectionId: string, userId: string) { const { error } = await getClient().from("after_dark_consents").upsert({ connection_id: connectionId, user_id: userId }); if (error) throw error }
export async function setAfterDarkEnabled(connectionId: string, enabled: boolean) { const { error } = await getClient().from("connection_settings").upsert({ connection_id: connectionId, after_dark_enabled: enabled, updated_at: new Date().toISOString() }); if (error) throw error }
export async function startDuel(connectionId: string, userId: string) { const { data, error } = await getClient().from("duel_sessions").insert({ connection_id: connectionId, created_by: userId, game_type: "more_likely" }).select("id").single(); if (error) throw error; return data.id as string }
export async function saveDuelMove(sessionId: string, userId: string, moveType: string, payload: Record<string, unknown>) { const { error } = await getClient().from("duel_moves").upsert({ session_id: sessionId, user_id: userId, move_type: moveType, payload }, { onConflict: "session_id,user_id,move_type" }); if (error) throw error }
export async function acceptInvite(token: string, userId: string) { const { data, error } = await getClient().rpc("accept_connection_invite", { invite_token_hash: await hashInviteToken(token), joining_user: userId }); if (error) throw error; return data as string }

export async function createQuestionRound(input: { connectionId: string; questionId: string; userId: string }) { const client = getClient(); const { data, error } = await client.from("question_rounds").insert({ connection_id: input.connectionId, question_id: input.questionId, created_by: input.userId }).select("id").single(); if (error) throw error; return data.id as string }
export async function revealQuestionRound(roundId: string) { const { data, error } = await getClient().rpc("reveal_question_round", { round_id: roundId }); if (error) throw error; return Boolean(data) }
export async function getQuestionRoundState(connectionId: string, questionId: string): Promise<{ round: { id: string; status: string; revealed_at: string | null } | null; answers: Array<{ user_id: string; answer: string }> }> { const client = getClient(); const { data: round, error: roundError } = await client.from("question_rounds").select("id,status,revealed_at").eq("connection_id", connectionId).eq("question_id", questionId).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (roundError) throw roundError; const { data: answers, error: answerError } = await client.from("question_answers").select("user_id,answer").eq("connection_id", connectionId).eq("question_id", questionId); if (answerError) throw answerError; return { round, answers: answers ?? [] } }
export async function hasMutualAfterDarkConsent(connectionId: string) { const { data, error } = await getClient().from("after_dark_consents").select("user_id").eq("connection_id", connectionId); if (error) throw error; return (data?.length ?? 0) >= 2 }
export async function saveAfterDarkAnswer(input: { connectionId: string; questionId: string; userId: string; answer: string }) { const { error } = await getClient().from("after_dark_answers").upsert({ connection_id: input.connectionId, question_id: input.questionId, user_id: input.userId, answer: input.answer.trim() }, { onConflict: "connection_id,question_id,user_id" }); if (error) throw error }

export type LovemeClient = ReturnType<typeof createClient>
